# Generated by Django 4.1.7 on 2023-03-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnavcontent',
            name='additional_js',
        ),
        migrations.RemoveField(
            model_name='subnavcontent',
            name='is_home',
        ),
        migrations.AddField(
            model_name='subnav',
            name='additional_js',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subnav',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_finish',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_highlight',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
